# Generated by Django 5.2.11 on 2026-02-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.CharField(max_length=50, verbose_name='借りた人')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('description', models.CharField(max_length=100, verbose_name='用途')),
                ('is_returned', models.BooleanField(default=False, verbose_name='返済済み')),
            ],
        ),
    ]
