# Generated by Django 5.2.14 on 2026-07-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='debt',
            name='foreign_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debt',
            name='foreign_currency',
            field=models.CharField(default='JPY', max_length=10),
        ),
    ]
