# Generated by Django 5.2.16 on 2026-08-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_debt_exchange_rate_debt_foreign_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='例: USD, EUR', max_length=3, unique=True, verbose_name='通貨コード')),
                ('rate', models.DecimalField(decimal_places=6, help_text='1外貨あたりの日本円 (JPY)', max_digits=12, verbose_name='対円レート')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='最終取得日時')),
            ],
            options={
                'verbose_name': '為替レート',
                'verbose_name_plural': '為替レート一覧',
            },
        ),
    ]
