# Generated by Django 5.2.16 on 2026-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='foreign_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
